micronaut:
  application:
    name: transfers-app
  security:
    enabled: false
  server:
    port: 8080
datasources:
  default:
    url: jdbc:h2:mem:devDb;INIT=RUNSCRIPT FROM 'classpath:init.sql';DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    packages-to-scan:
      packages:
        - 'org.tb.transfer'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true